fe_last_online.controller.felastonline:
    path: /la/{action}
    defaults:
        _scope: frontend
        _token_check: false
        _controller: 'ContaoFeUserOnlineBundle\Controller\FelastonlineController'